import numpy as np
SCREEN_WIDTH = 512
SCREEN_HEIGHT = 512
K_LEFT = ord('a')
K_RIGHT = ord('d')
K_UP = ord('w')
K_DOWN = ord('s')
SCALE = 64
BUTTON_FEEDBACK = False

DAYLIGHT_SPEED = .1
DAYLIGHT_DIVISOR = 1/DAYLIGHT_SPEED
DARKNESS_SHIFT = 0.0
SUN_BRIGHTNESS = .005
SUN_DARKNESS = .005
UPDATE = True


WAVE_JOYSTICK_CONTRIBUTION = 0.2
WAVE_SPEED = 10
WAVE_AMPLITUDE = 60
WAKE_AMPLITUDE = 110
WAVE_TIME_SCALE = -.4
WATER_RANDOMNESS = 0
WIND_SPEED=0.15

WAKE_FREQ = .8
WAKE_RADIUSISH = 0.029  # 1/WIDTH?? lower is wider so like 1/radius
WAVE_SHIP_MOVEMENT_FREQ = np.array([2,4])
WAVE_SHIP_MOVEMENT = np.array([.5,.75])
WIND_VECTOR = np.array([-1,.5])*WIND_SPEED

SPEED = 1
ACCELERATION=.022
MAX_MAG = 350
JOYSTICK_CONTRIBUTION=0.04
PRESS_TO_MOVE = True

DARK_COLOR = np.array([50,20,48])
LIGHT_COLOR = np.array([252,255,245])

CAMERA_ANGLE = np.array([128,150,128])
SOURCE_CUTOFF = .25